on: [push]
jobs:
  test-compile-v-code:
    runs-on: ubuntu-latest
    steps:
      - name: setup v compiler
        run: | 
          sudo apt install gcc
          git clone https://github.com/vlang/v ${{runner.workspace}}/v
          cd ${{runner.workspace }}/v
          make
          ./v symlink
      - name: compile v code
        uses: actions/checkout@v2
      - run: |
          v -cc gcc -prod -gc boehm -show-timings -compress .    