on: [push]
jobs:
  test-compile-v-code:
    runs-on: ubuntu-latest
    steps:
      - name: get dependencies
        run: |
          sudo apt install gcc libgc-dev
      - name: setup v compiler
        run: | 
          git clone https://github.com/vlang/v ${{runner.workspace}}/v
          cd ${{runner.workspace }}/v
          make
          ./v symlink
      - name: checkount v code
        uses: actions/checkout@v2
      - name: compile v code
        run: |
          v run main.v